SUCCESS_STATUSES = [
    "queued",
    "probing",
    "extracting_audio",
    "transcribing",
    "detecting_scenes",
    "generating_candidates",
    "scoring_candidates",
    "selecting_clips",
    "rendering_normal_clips",
    "rendering_shorts",
    "packaging_zip",
    "completed",
]

PROGRESS_MAP = {
    "uploaded": 0,
    "queued": 5,
    "probing": 10,
    "extracting_audio": 18,
    "transcribing": 30,
    "correcting_subtitles": 31,
    "detecting_scenes": 40,
    "generating_candidates": 50,
    "scoring_candidates": 65,
    "selecting_clips": 72,
    "reselecting_clips": 72,
    "preparing_clip_review": 73,
    "awaiting_clip_review": 76,
    "preparing_subtitle_review": 77,
    "awaiting_subtitle_review": 80,
    "rendering_normal_clips": 82,
    "rendering_shorts": 92,
    "packaging_zip": 98,
    "completed": 100,
    "failed": 100,
}

CURRENT_STEP_MAP = {
    "uploaded": "Uploaded",
    "queued": "Queued",
    "probing": "Reading video metadata",
    "extracting_audio": "Extracting audio",
    "transcribing": "Transcribing audio",
    "correcting_subtitles": "Correcting subtitles",
    "detecting_scenes": "Detecting scenes",
    "generating_candidates": "Generating clip candidates",
    "scoring_candidates": "Scoring candidates",
    "selecting_clips": "Selecting clips",
    "reselecting_clips": "Reselecting clips",
    "preparing_clip_review": "Preparing clip plan previews",
    "awaiting_clip_review": "Waiting for clip plan review",
    "preparing_subtitle_review": "Preparing subtitle review videos",
    "awaiting_subtitle_review": "Waiting for subtitle review",
    "rendering_normal_clips": "Rendering normal clips",
    "rendering_shorts": "Rendering shorts",
    "packaging_zip": "Packaging ZIP",
    "completed": "Completed",
    "failed": "Failed",
}
